export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_EVENTO = 'SET_EVENTO';
export const SET_CURRENT_EVENTO = 'SET_CURRENT_EVENTO';
